<a href="https://colab.research.google.com/github/gcbenito1-blip/elective_streamlit/blob/preprocessing/bulk_translate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install googletrans
# !pip install bulk-translate
# !pip install deep-translator

!pip install bulk-translate==0.25.1
!pip install googletrans==3.1.0a

Requirement already satisfied: bulk-translate==0.25.1 in /usr/local/lib/python3.12/dist-packages (0.25.1)
Requirement already satisfied: googletrans==3.1.0a in /usr/local/lib/python3.12/dist-packages (3.1.0a0)
Requirement already satisfied: httpx==0.13.3 in /usr/local/lib/python3.12/dist-packages (from googletrans==3.1.0a) (0.13.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (2026.2.25)
Requirement already satisfied: hstspreload in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (2025.1.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (1.3.1)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (3.0.4)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==3.1.0a) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.12/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a) (0.9.0)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.12/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.12/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a) (3.0.0)

In [ ]:
import pandas as pd
import asyncio
from googletrans import Translator
import unicodedata
from tqdm.notebook import trange, tqdm
from time import sleep
import re

In [ ]:
tgl_df = pd.read_csv('tgl_review.csv', index_col=0)
items = tgl_df['clean'].tolist()
translated = []

In [ ]:
def translate_bulk_sync(items, batch_size=20):
    results = []
    translator = Translator()

    with tqdm(total=len(items)) as pbar:
        for i in range(0, len(items), batch_size):
            batch = items[i:i+batch_size]

            translations = translator.translate(batch, dest='en')

            results.extend([t.text for t in translations])
            pbar.update(len(batch))

    return results

translated = translate_bulk_sync(items)
tgl_df['translated'] = translated

100%|██████████| 5925/5925 [1:27:26<00:00,  1.13it/s]

In [ ]:
tgl_df

/usr/local/lib/python3.12/dist-packages/google/colab/_interactive_table_hint_button.py:111: RuntimeWarning: coroutine 'translate_bulk' was never awaited
  _last_noninteractive_df.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

,reviewId,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog,clean,translated
4,9b9c244d-df83-4915-a7c2-18fbfb637904,4,0,2.7.1,2026-04-16 08:52:50,1,ok mas mapamadali ang gusto natin thru egov...,ok what we want is easier thru egov...
11,7d529fed-fb53-46be-96bc-75d677a6e07f,5,0,2.7.1,2026-04-16 05:22:59,1,maganda app,nice app
14,8263a442-56cb-4d10-a93c-a26636278afe,1,0,2.7.1,2026-04-16 04:17:16,1,ambagal please improve it. anlaki ng budget ny...,slowly please improve it. how big is your budg...
27,06a0beb8-eeed-46b7-8248-557ac320d026,5,0,2.7.1,2026-04-16 02:10:47,1,akala ko hindi ko ma verify ang aking gcash da...,I thought I couldn't verify my gcash because m...
28,a3ac8d5c-d458-438c-9505-1c3f29636c7b,5,0,2.7.1,2026-04-16 02:05:59,1,ang ganda nakikita ko ulit ang national id ko,it's nice to see my national id again
...,...,...,...,...,...,...,...,...
43887,7c4c8f86-a802-4e7f-8fd8-8582a75e0aba,2,1,1.1.2,2023-06-02 09:25:59,1,di ako maka veryfy ayaw mag scan ng philsys ko...,I can't veryfy. My philsys doesn't want to sca...
43894,3f2059c6-71c6-4f2e-bdc7-451621c730de,5,1,1.1.2,2023-06-02 07:01:57,1,its amazing,its amazing
43895,eb3c7898-d67f-4318-a2c8-405d6127a2db,5,1,1.1.2,2023-06-02 06:47:04,1,accessible at madaling gamitin ganda gamitin d...,"accessible and easy to use, nice to use becaus..."
43900,ffe92e5d-c018-4502-a834-c7d48eecac53,3,5,1.1.2,2023-06-02 03:45:24,1,ayaw magproceed after magcaptuee ng id may box...,doesn't want to proceed after captuee id only ...
43905,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,5,15,1.1.1,2023-06-01 12:04:33,1,maganda at madali ang egov.ph app,the egov.ph app is nice and easy

In [ ]:
tgl_df.to_csv('tgl_translated.csv')

In [ ]:
df1 = pd.read_csv('tgl_translated.csv', index_col=0)
df2 = pd.read_csv('eng_review.csv', index_col=0)

combined = pd.concat([df1, df2])
combined.sort_index(inplace=True)

In [ ]:
combined

,reviewId,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog,clean,translated
0,8b1f3376-704d-404b-a6df-31669ec01bc4,5,0,2.7.1,2026-04-16 11:20:49,0,thanks this apps. because for me this apps is ...,thanks this apps. because for me this apps is ...
1,96d73a45-1777-49ef-8928-118a48d7b367,5,0,2.7.1,2026-04-16 10:23:03,0,happyeasy and fast and even first time to crea...,happyeasy and fast and even first time to crea...
2,3728b718-bafd-4638-aa74-53fec7d7558d,5,0,2.7.1,2026-04-16 09:13:39,0,perfect,perfect
3,2f82efd1-848f-4b33-b10e-69f4479ca728,5,0,2.7.1,2026-04-16 09:06:02,0,absolutely great...,absolutely great...
4,9b9c244d-df83-4915-a7c2-18fbfb637904,4,0,2.7.1,2026-04-16 08:52:50,1,ok mas mapamadali ang gusto natin thru egov...,ok what we want is easier thru egov...
...,...,...,...,...,...,...,...,...
43902,d039976d-d0d8-4867-8a57-9b7b568ce65f,5,1,1.1.2,2023-06-02 02:38:43,0,nice! first app ng gov!,nice! first app ng gov!
43903,1abdfb9f-eb73-45b8-a6ea-e8ab42b1b0c3,5,0,1.1.2,2023-06-02 02:13:54,0,first!,first!
43904,8fb3ca76-7748-4a25-a171-a3f112bac57d,1,20,1.1.1,2023-06-01 12:04:40,0,please put in suffix the ii after sr jr it fol...,please put in suffix the ii after sr jr it fol...
43905,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,5,15,1.1.1,2023-06-01 12:04:33,1,maganda at madali ang egov.ph app,the egov.ph app is nice and easy
43906,41ae93d4-ac95-44ac-b6d5-c41b728ac605,5,23,1.1.0,2023-05-31 19:04:30,0,5th person to download the app. looking forwar...,5th person to download the app. looking forwar...

In [ ]:
combined.isna().sum()

reviewId                0
score                   0
thumbsUpCount           0
reviewCreatedVersion    0
at                      0
is_tagalog              0
clean                   0
translated              0
dtype: int64

In [ ]:
combined.drop(columns=['clean', 'is_tagalog'], inplace=True)
combined['at'] = pd.to_datetime(combined['at'], format="%Y-%m-%d %H:%M:%S")
combined

,reviewId,score,thumbsUpCount,reviewCreatedVersion,at,translated
0,8b1f3376-704d-404b-a6df-31669ec01bc4,5,0,2.7.1,2026-04-16 11:20:49,thanks this apps. because for me this apps is ...
1,96d73a45-1777-49ef-8928-118a48d7b367,5,0,2.7.1,2026-04-16 10:23:03,happyeasy and fast and even first time to crea...
2,3728b718-bafd-4638-aa74-53fec7d7558d,5,0,2.7.1,2026-04-16 09:13:39,perfect
3,2f82efd1-848f-4b33-b10e-69f4479ca728,5,0,2.7.1,2026-04-16 09:06:02,absolutely great...
4,9b9c244d-df83-4915-a7c2-18fbfb637904,4,0,2.7.1,2026-04-16 08:52:50,ok what we want is easier thru egov...
...,...,...,...,...,...,...
43902,d039976d-d0d8-4867-8a57-9b7b568ce65f,5,1,1.1.2,2023-06-02 02:38:43,nice! first app ng gov!
43903,1abdfb9f-eb73-45b8-a6ea-e8ab42b1b0c3,5,0,1.1.2,2023-06-02 02:13:54,first!
43904,8fb3ca76-7748-4a25-a171-a3f112bac57d,1,20,1.1.1,2023-06-01 12:04:40,please put in suffix the ii after sr jr it fol...
43905,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,5,15,1.1.1,2023-06-01 12:04:33,the egov.ph app is nice and easy
43906,41ae93d4-ac95-44ac-b6d5-c41b728ac605,5,23,1.1.0,2023-05-31 19:04:30,5th person to download the app. looking forwar...

In [ ]:
combined.dtypes

reviewId                        object
score                            int64
thumbsUpCount                    int64
reviewCreatedVersion            object
at                      datetime64[ns]
translated                      object
dtype: object

In [ ]:
combined.shape

(43907, 6)

In [ ]:
combined.to_csv('final_dataset.csv')