<a href="https://colab.research.google.com/github/gcbenito1-blip/elective_streamlit/blob/preprocessing/preprocessing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install translate
!pip install google-play-scraper
!pip install langdetect
!pip install translate
!pip install fast-langdetect
!pip install clean-text[gpl]

Collecting translate
  Downloading translate-3.8.0-py2.py3-none-any.whl.metadata (9.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from translate) (8.3.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from translate) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from translate) (2.32.4)
Collecting libretranslatepy==2.1.1 (from translate)
  Downloading libretranslatepy-2.1.1-py3-none-any.whl.metadata (233 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2026.2.25)
Downloading translate-3.8.0-py2.py3-none-any.whl (14 kB)
Downloading libretranslatepy-2.1.1-py3-none-any.whl (3.2 kB)
Installing collected packages: libretranslatepy, translate
Successfully installed libretranslatepy-2.1.1 translate-3.8.0
Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.3 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=e176fba79612943dc926cd9e98e876ce6ca421905e031f1523b49524b44717e6
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Requirement already satisfied: translate in /usr/local/lib/python3.12/dist-packages (3.8.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from translate) (8.3.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from translate) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from translate) (2.32.4)
Requirement already satisfied: libretranslatepy==2.1.1 in /usr/local/lib/python3.12/dist-packages (from translate) (2.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->translate) (2026.2.25)
Collecting fast-langdetect
  Downloading fast_langdetect-1.0.0-py3-none-any.whl.metadata (11 kB)
Collecting robust-downloader>=0.0.2 (from fast-langdetect)
  Downloading robust_downloader-0.0.2-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: requests>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from fast-langdetect) (2.32.4)
Collecting fasttext-predict>=0.9.2.4 (from fast-langdetect)
  Downloading fasttext_predict-0.9.2.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.3->fast-langdetect) (2026.2.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from robust-downloader>=0.0.2->fast-langdetect) (4.67.3)
Collecting colorlog (from robust-downloader>=0.0.2->fast-langdetect)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Downloading fast_langdetect-1.0.0-py3-none-any.whl (789 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.9/789.9 kB 12.2 MB/s eta 0:00:00
Downloading fasttext_predict-0.9.2.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.1/296.1 kB 23.8 MB/s eta 0:00:00
Downloading robust_downloader-0.0.2-py3-none-any.whl (15 kB)
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: fasttext-predict, colorlog, robust-downloader, fast-langdetect
Successfully installed colorlog-6.10.1 fast-langdetect-1.0.0 fasttext-predict-0.9.2.4 robust-downloader-0.0.2
Collecting clean-text[gpl]
  Downloading clean_text-0.7.1-py3-none-any.whl.metadata (9.1 kB)
Collecting emoji>=2.1.0 (from clean-text[gpl])
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting ftfy<7.0,>=6.0 (from clean-text[gpl])
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting unidecode<2.0.0,>=1.1.1 (from clean-text[gpl])
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy<7.0,>=6.0->clean-text[gpl]) (0.6.0)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.9 MB/s eta 0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.0 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 14.0 MB/s eta 0:00:00
Downloading clean_text-0.7.1-py3-none-any.whl (15 kB)
Installing collected packages: unidecode, ftfy, emoji, clean-text
Successfully installed clean-text-0.7.1 emoji-2.15.0 ftfy-6.3.1 unidecode-1.4.0

In [3]:
from google_play_scraper import Sort, reviews_all
from langdetect import detect
# from fast_langdetect import detect_language
import pandas as pd
import unicodedata
import re

In [ ]:
def scrape_data():

    results = reviews_all(
        'egov.app',
        lang='en',
        sort=Sort.NEWEST,
    )

    return results

def detect_lang(row):
    try:
        if detect(row['content']) == 'tl':
            return 1
        else:
            return 0
    except:
        return 0

In [ ]:
review_dataset = scrape_data()
df = pd.DataFrame(review_dataset)

df = df.reindex(columns=[
    'reviewId', 'content', 'score', 'thumbsUpCount',
    'reviewCreatedVersion', 'at'
])

df.index.name = 'index'
df['content'] = df['content'].astype(str).str.lower()
df['is_tagalog'] = df.apply(detect_lang, axis=1)
df.to_csv('all_reviews.csv')

In [ ]:
df

,reviewId,content,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog,clean
index,,,,,,,,
0,8b1f3376-704d-404b-a6df-31669ec01bc4,thanks this apps. because for me this apps is ...,5,0,2.7.1,2026-04-16 11:20:49,0,thanks this apps. because for me this apps is ...
1,96d73a45-1777-49ef-8928-118a48d7b367,"happy,easy and fast ,and even first time to cr...",5,0,2.7.1,2026-04-16 10:23:03,0,"happy,easy and fast ,and even first time to cr..."
2,3728b718-bafd-4638-aa74-53fec7d7558d,perfect,5,0,2.7.1,2026-04-16 09:13:39,0,perfect
3,2f82efd1-848f-4b33-b10e-69f4479ca728,absolutely great...,5,0,None,2026-04-16 09:06:02,0,absolutely great...
4,9b9c244d-df83-4915-a7c2-18fbfb637904,ok mas mapamadali ang gusto natin thru egov...,4,0,2.7.1,2026-04-16 08:52:50,1,ok mas mapamadali ang gusto natin thru egov...
...,...,...,...,...,...,...,...,...
44511,d039976d-d0d8-4867-8a57-9b7b568ce65f,nice! first app ng gov!,5,1,1.1.2,2023-06-02 02:38:43,0,nice! first app ng gov!
44512,1abdfb9f-eb73-45b8-a6ea-e8ab42b1b0c3,first!,5,0,1.1.2,2023-06-02 02:13:54,0,first!
44513,8fb3ca76-7748-4a25-a171-a3f112bac57d,please put in suffix the ii after sr jr it fol...,1,20,1.1.1,2023-06-01 12:04:40,0,please put in suffix the ii after sr jr it fol...
44514,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,maganda at madali ang egov.ph app,5,15,1.1.1,2023-06-01 12:04:33,1,maganda at madali ang egov.ph app
44515,41ae93d4-ac95-44ac-b6d5-c41b728ac605,5th person to download the app. looking forwar...,5,23,1.1.0,2023-05-31 19:04:30,0,5th person to download the app. looking forwar...

In [ ]:
# from cleantext import clean
# df['clean'] = df['content'].apply(
#     lambda x: clean(
#         x,
#         fix_unicode=True,
#         no_line_breaks=True,
#         no_code=True,
#         no_urls=True,
#         no_emails=True,
#         no_phone_numbers=True,
#         no_ip_addresses=True,
#         no_file_paths=True,
#         no_emoji=True,
#         no_currency_symbols=True
#     )
# )

In [15]:
df = pd.read_csv('all_reviews.csv')
df

,index,reviewId,content,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog
0,0,8b1f3376-704d-404b-a6df-31669ec01bc4,thanks this apps. because for me this apps is ...,5,0,2.7.1,2026-04-16 11:20:49,0
1,1,96d73a45-1777-49ef-8928-118a48d7b367,"happy,easy and fast ,and even first time to cr...",5,0,2.7.1,2026-04-16 10:23:03,0
2,2,3728b718-bafd-4638-aa74-53fec7d7558d,perfect,5,0,2.7.1,2026-04-16 09:13:39,0
3,3,2f82efd1-848f-4b33-b10e-69f4479ca728,absolutely great...,5,0,NaN,2026-04-16 09:06:02,0
4,4,9b9c244d-df83-4915-a7c2-18fbfb637904,ok mas mapamadali ang gusto natin thru egov...,4,0,2.7.1,2026-04-16 08:52:50,1
...,...,...,...,...,...,...,...,...
44511,44511,d039976d-d0d8-4867-8a57-9b7b568ce65f,nice! first app ng gov!,5,1,1.1.2,2023-06-02 02:38:43,0
44512,44512,1abdfb9f-eb73-45b8-a6ea-e8ab42b1b0c3,first!,5,0,1.1.2,2023-06-02 02:13:54,0
44513,44513,8fb3ca76-7748-4a25-a171-a3f112bac57d,please put in suffix the ii after sr jr it fol...,1,20,1.1.1,2023-06-01 12:04:40,0
44514,44514,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,maganda at madali ang egov.ph app,5,15,1.1.1,2023-06-01 12:04:33,1
44515,44515,41ae93d4-ac95-44ac-b6d5-c41b728ac605,5th person to download the app. looking forwar...,5,23,1.1.0,2023-05-31 19:04:30,0

In [24]:
def clean_text(text):
    text = unicodedata.normalize('NFKC', str(text))#unicode formatting
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)#http
    text = re.sub(r'@\w+|#\w+', '', text) #removed mentions/hashtags
    text = re.sub(r'<.*?>', '', text) #removed html
    text = re.sub(r'[^\w\s\.!?@#]', '', text) #symbols
    text = re.sub(r'\s+', ' ', text) #space normalization
    return text.lower().strip() #lowerspace and whitespace trimming

emoji_pattern = re.compile(
    "["
    "\U0001F600-\U0001F64F"
    "\U0001F300-\U0001F5FF"
    "\U0001F680-\U0001F6FF"
    "\U0001F700-\U0001F77F"
    "\U0001F780-\U0001F7FF"
    "\U0001F800-\U0001F8FF"
    "\U0001F900-\U0001F9FF"
    "\U0001FA00-\U0001FAFF"
    "\U00002700-\U000027BF"
    "\U00002600-\U000026FF"
    "]+",
    flags=re.UNICODE
)

def remove_emoji(text):
    return emoji_pattern.sub('', str(text))

df = df.copy()

df['clean'] = (
    df['content']
    .astype(str)
    .apply(remove_emoji)
    .apply(clean_text)
)

df.to_csv('clean_dataset.csv', index=False)
df1 = pd.read_csv('clean_dataset.csv')
df1.isna().sum()

index                      0
reviewId                   0
content                    5
score                      0
thumbsUpCount              0
reviewCreatedVersion    5159
at                         0
is_tagalog                 0
clean                      5
dtype: int64

In [25]:
df1['reviewCreatedVersion'] = df1['reviewCreatedVersion'].ffill()
df1.isna().sum()

index                   0
reviewId                0
content                 5
score                   0
thumbsUpCount           0
reviewCreatedVersion    0
at                      0
is_tagalog              0
clean                   5
dtype: int64

In [33]:
import numpy as np

df1 = df1.replace("", np.nan).dropna()
df1.isna().sum()

index                   0
reviewId                0
content                 0
score                   0
thumbsUpCount           0
reviewCreatedVersion    0
at                      0
is_tagalog              0
clean                   0
dtype: int64

In [60]:
df1.to_csv('cleaned_dataset.csv', index=False)

In [62]:
df1 = pd.read_csv('cleaned_dataset.csv')
df_eng = df1[df1['is_tagalog'] ==0].copy()
df_eng['translated'] = df_eng['clean']
df_eng.to_csv('eng_review.csv')
df_tgl = df1[df1['is_tagalog'] ==1].copy()
df_tgl.to_csv('tgl_review.csv')

In [63]:
df_eng

,reviewId,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog,clean,translated
0,8b1f3376-704d-404b-a6df-31669ec01bc4,5,0,2.7.1,2026-04-16 11:20:49,0,thanks this apps. because for me this apps is ...,thanks this apps. because for me this apps is ...
1,96d73a45-1777-49ef-8928-118a48d7b367,5,0,2.7.1,2026-04-16 10:23:03,0,happyeasy and fast and even first time to crea...,happyeasy and fast and even first time to crea...
2,3728b718-bafd-4638-aa74-53fec7d7558d,5,0,2.7.1,2026-04-16 09:13:39,0,perfect,perfect
3,2f82efd1-848f-4b33-b10e-69f4479ca728,5,0,2.7.1,2026-04-16 09:06:02,0,absolutely great...,absolutely great...
5,3b2869c4-bbd6-4a2e-8c50-b10634dbbe2c,1,0,2.7.1,2026-04-16 08:23:50,0,trash,trash
...,...,...,...,...,...,...,...,...
43901,5f8d80d1-e4ce-47ee-9ba0-bc6e684000f9,1,2,1.1.2,2023-06-02 02:39:43,0,newly signed up and mpin is invalid.,newly signed up and mpin is invalid.
43902,d039976d-d0d8-4867-8a57-9b7b568ce65f,5,1,1.1.2,2023-06-02 02:38:43,0,nice! first app ng gov!,nice! first app ng gov!
43903,1abdfb9f-eb73-45b8-a6ea-e8ab42b1b0c3,5,0,1.1.2,2023-06-02 02:13:54,0,first!,first!
43904,8fb3ca76-7748-4a25-a171-a3f112bac57d,1,20,1.1.1,2023-06-01 12:04:40,0,please put in suffix the ii after sr jr it fol...,please put in suffix the ii after sr jr it fol...
43906,41ae93d4-ac95-44ac-b6d5-c41b728ac605,5,23,1.1.0,2023-05-31 19:04:30,0,5th person to download the app. looking forwar...,5th person to download the app. looking forwar...

In [54]:
df_tgl

,reviewId,score,thumbsUpCount,reviewCreatedVersion,at,is_tagalog,clean
4,9b9c244d-df83-4915-a7c2-18fbfb637904,4,0,2.7.1,2026-04-16 08:52:50,1,ok mas mapamadali ang gusto natin thru egov...
11,7d529fed-fb53-46be-96bc-75d677a6e07f,5,0,2.7.1,2026-04-16 05:22:59,1,maganda app
14,8263a442-56cb-4d10-a93c-a26636278afe,1,0,2.7.1,2026-04-16 04:17:16,1,ambagal please improve it. anlaki ng budget ny...
27,06a0beb8-eeed-46b7-8248-557ac320d026,5,0,2.7.1,2026-04-16 02:10:47,1,akala ko hindi ko ma verify ang aking gcash da...
28,a3ac8d5c-d458-438c-9505-1c3f29636c7b,5,0,2.7.1,2026-04-16 02:05:59,1,ang ganda nakikita ko ulit ang national id ko
...,...,...,...,...,...,...,...
43887,7c4c8f86-a802-4e7f-8fd8-8582a75e0aba,2,1,1.1.2,2023-06-02 09:25:59,1,di ako maka veryfy ayaw mag scan ng philsys ko...
43894,3f2059c6-71c6-4f2e-bdc7-451621c730de,5,1,1.1.2,2023-06-02 07:01:57,1,its amazing
43895,eb3c7898-d67f-4318-a2c8-405d6127a2db,5,1,1.1.2,2023-06-02 06:47:04,1,accessible at madaling gamitin ganda gamitin d...
43900,ffe92e5d-c018-4502-a834-c7d48eecac53,3,5,1.1.2,2023-06-02 03:45:24,1,ayaw magproceed after magcaptuee ng id may box...
43905,8d843fdc-3e20-49ff-9cb6-5e811cb09f12,5,15,1.1.1,2023-06-01 12:04:33,1,maganda at madali ang egov.ph app